# axios-dav home-manager module
# Generates vdirsyncer, khal, and khard configurations
{
  config,
  lib,
  pkgs,
  osConfig ? { },
  ...
}:
let
  # Get config from NixOS module or standalone home-manager config
  cfg = osConfig.services.axios-dav or config.services.axios-dav or { };
  calendarEnabled = cfg.calendar.enable or false;
  contactsEnabled = cfg.contacts.enable or false;
  enabled = cfg.enable or false;

  # Calendar accounts (from NixOS module)
  calendarAccounts = cfg.calendar.accounts or { };
  contactsAccounts = cfg.contacts.accounts or { };

  # Sync settings
  syncFrequency = cfg.sync.frequency or "5m";
  conflictResolution = cfg.sync.conflictResolution or "remote";

  # Convert frequency like "5m" to OnCalendar format
  frequencyToOnCalendar =
    freq:
    let
      # Parse "5m" -> 5 minutes, "1h" -> hourly, etc.
      value = lib.strings.toInt (builtins.head (builtins.match "([0-9]+).*" freq));
      unit = builtins.head (builtins.match "[0-9]+([a-z]+)" freq);
    in
    if unit == "m" then
      "*:0/${toString value}"
    else if unit == "h" then
      "*:00"
    else
      "*:0/5"; # default to 5 min

  # Conflict resolution mapping
  conflictString = if conflictResolution == "remote" then "b wins" else "a wins";

  # Base paths
  calendarsPath = "~/.calendars";
  contactsPath = "~/.contacts";
  statusPath = "~/.local/share/vdirsyncer/status/";

  # Generate vdirsyncer config for a single calendar account
  generateCalendarStorage =
    name: account:
    let
      localPath = "${calendarsPath}/${name}/";
      collections = if account.readOnly or false then ''["from b"]'' else ''["from a", "from b"]'';
    in
    ''
      [pair cal_${name}]
      a = "cal_${name}_local"
      b = "cal_${name}_remote"
      collections = ${collections}
      conflict_resolution = "${conflictString}"
      metadata = ["color", "displayname"]

      [storage cal_${name}_local]
      type = "filesystem"
      path = "${localPath}"
      fileext = ".ics"

      ${generateRemoteCalendarStorage name account}
    '';

  # Generate remote storage config based on account type
  generateRemoteCalendarStorage =
    name: account:
    if account.type == "google" then
      ''
        [storage cal_${name}_remote]
        type = "google_calendar"
        token_file = "${toString account.tokenFile}"
        client_id = "${account.clientId}"
        client_secret.fetch = ["command", "cat", "${toString account.clientSecretFile}"]
      ''
    else if account.type == "caldav" then
      ''
        [storage cal_${name}_remote]
        type = "caldav"
        url = "${account.url}"
        username = "${account.username}"
        password.fetch = ["command", "cat", "${toString account.passwordFile}"]
      ''
    else if account.type == "http" then
      ''
        [storage cal_${name}_remote]
        type = "http"
        url = "${account.icsUrl}"
      ''
    else
      throw "Unknown calendar type: ${account.type}";

  # Generate vdirsyncer config for a single contacts account
  generateContactsStorage =
    name: account:
    let
      localPath = "${contactsPath}/${name}/";
    in
    ''
      [pair contacts_${name}]
      a = "contacts_${name}_local"
      b = "contacts_${name}_remote"
      collections = ["from a", "from b"]
      conflict_resolution = "${conflictString}"

      [storage contacts_${name}_local]
      type = "filesystem"
      path = "${localPath}"
      fileext = ".vcf"

      ${generateRemoteContactsStorage name account}
    '';

  # Generate remote contacts storage config
  generateRemoteContactsStorage =
    name: account:
    if account.type == "google" then
      ''
        [storage contacts_${name}_remote]
        type = "google_contacts"
        token_file = "${toString account.tokenFile}"
        client_id = "${account.clientId}"
        client_secret.fetch = ["command", "cat", "${toString account.clientSecretFile}"]
      ''
    else if account.type == "carddav" then
      ''
        [storage contacts_${name}_remote]
        type = "carddav"
        url = "${account.url}"
        username = "${account.username}"
        password.fetch = ["command", "cat", "${toString account.passwordFile}"]
      ''
    else
      throw "Unknown contacts type: ${account.type}";

  # Complete vdirsyncer config
  vdirsyncerConfig = ''
    # Auto-generated by axios-dav - do not edit manually
    # Source: services.axios-dav in your NixOS configuration

    [general]
    status_path = "${statusPath}"

    ${lib.concatStringsSep "\n" (lib.mapAttrsToList generateCalendarStorage calendarAccounts)}
    ${lib.optionalString contactsEnabled (
      lib.concatStringsSep "\n" (lib.mapAttrsToList generateContactsStorage contactsAccounts)
    )}
  '';

  # Generate khal config
  generateKhalCalendarEntry = name: account: ''
    [[cal_${name}]]
    path = ${calendarsPath}/${name}/*
    type = discover
    ${lib.optionalString (account.readOnly or false) "readonly = True"}
  '';

  khalConfig = ''
    # Auto-generated by axios-dav - do not edit manually

    [calendars]
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList generateKhalCalendarEntry calendarAccounts)}

    [default]
    ${lib.optionalString (cfg.calendar.defaultCalendar or null != null) ''
      default_calendar = cal_${cfg.calendar.defaultCalendar}
    ''}
    highlight_event_days = True

    [locale]
    timeformat = %H:%M
    dateformat = %Y-%m-%d
    longdateformat = %A, %B %d, %Y
    datetimeformat = %Y-%m-%d %H:%M
    longdatetimeformat = %A, %B %d, %Y %H:%M

    [view]
    agenda_event_format = {calendar-color}{cancelled}{start-end-time-style} {title}{repeat-symbol}{reset}
  '';

  # Generate khard config
  generateKhardAddressbookEntry = name: account: ''
    [[contacts_${name}]]
    path = ${contactsPath}/${name}/
  '';

  khardConfig = ''
    # Auto-generated by axios-dav - do not edit manually

    [general]
    default_action = list
    editor = $EDITOR
    merge_editor = vimdiff

    [addressbooks]
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList generateKhardAddressbookEntry contactsAccounts)}

    [contact table]
    display = formatted_name
    group_by_addressbook = yes
    reverse = no
    show_nicknames = no
    show_uids = no
    sort = last_name
    localize_dates = yes
  '';
in
{
  # Allow this module to work standalone (without NixOS module)
  options.services.axios-dav = lib.mkOption {
    type = lib.types.attrs;
    default = { };
    description = "axios-dav configuration (usually set via NixOS module)";
  };

  config = lib.mkIf enabled {
    # Install user packages
    home.packages =
      with pkgs;
      [
        vdirsyncer
        khal
      ]
      ++ lib.optionals contactsEnabled [ khard ];

    # vdirsyncer configuration
    xdg.configFile."vdirsyncer/config" = lib.mkIf calendarEnabled { text = vdirsyncerConfig; };

    # khal configuration
    xdg.configFile."khal/config" = lib.mkIf calendarEnabled { text = khalConfig; };

    # khard configuration (if contacts enabled)
    xdg.configFile."khard/khard.conf" = lib.mkIf contactsEnabled { text = khardConfig; };

    # Create calendar directories
    home.file = lib.mkMerge [
      # Calendar directories
      (lib.mkIf calendarEnabled (
        lib.mapAttrs' (
          name: _:
          lib.nameValuePair ".calendars/${name}/.keep" {
            text = "";
          }
        ) calendarAccounts
      ))
      # Contacts directories
      (lib.mkIf contactsEnabled (
        lib.mapAttrs' (
          name: _:
          lib.nameValuePair ".contacts/${name}/.keep" {
            text = "";
          }
        ) contactsAccounts
      ))
    ];

    # Systemd user service for vdirsyncer sync
    systemd.user.services.vdirsyncer-sync = lib.mkIf calendarEnabled {
      Unit = {
        Description = "vdirsyncer: sync calendars and contacts";
        After = [ "network-online.target" ];
        Wants = [ "network-online.target" ];
      };
      Service = {
        Type = "oneshot";
        ExecStart = "${pkgs.vdirsyncer}/bin/vdirsyncer sync";
        StandardOutput = "journal";
        StandardError = "journal";
      };
    };

    # Timer for periodic sync
    systemd.user.timers.vdirsyncer-sync = lib.mkIf calendarEnabled {
      Unit.Description = "Run vdirsyncer sync periodically";
      Timer = {
        OnCalendar = frequencyToOnCalendar syncFrequency;
        Persistent = true;
        RandomizedDelaySec = "30s";
      };
      Install.WantedBy = [ "timers.target" ];
    };

    # Systemd service for metasync (metadata like colors, names)
    systemd.user.services.vdirsyncer-metasync = lib.mkIf calendarEnabled {
      Unit = {
        Description = "vdirsyncer: metasync (names/colors)";
        After = [ "network-online.target" ];
      };
      Service = {
        Type = "oneshot";
        ExecStart = "${pkgs.vdirsyncer}/bin/vdirsyncer metasync";
        StandardOutput = "journal";
        StandardError = "journal";
      };
    };

    # Timer for daily metasync
    systemd.user.timers.vdirsyncer-metasync = lib.mkIf calendarEnabled {
      Unit.Description = "Run vdirsyncer metasync daily";
      Timer = {
        OnCalendar = "daily";
        Persistent = true;
        RandomizedDelaySec = "5m";
      };
      Install.WantedBy = [ "timers.target" ];
    };

    # Initial discovery service (runs once after first sync)
    systemd.user.services.vdirsyncer-discover = lib.mkIf calendarEnabled {
      Unit = {
        Description = "vdirsyncer: discover collections";
        After = [ "network-online.target" ];
      };
      Service = {
        Type = "oneshot";
        ExecStart = "${pkgs.bash}/bin/bash -c '${pkgs.vdirsyncer}/bin/vdirsyncer discover --yes || true'";
        StandardOutput = "journal";
        StandardError = "journal";
      };
    };

    # MCP server configuration
    # TODO: Add mcp-dav to MCP config when mcp.enable = true
  };
}
